### ISSUE TITLE
Docker - Raspberry Pi 4 - Armv7 build?

### ISSUE THREAD

**Issue by kllngtme** [sundowndev/PhoneInfoga#725]
Hi, is it possible to create a docker image for the raspberry pi architecture? It's a ARMV7 build.

When I try to run it up in a docker environment I'm getting a hard crash:
```
phoneinfoga    | standard_init_linux.go:219: exec user process caused: exec format error
phoneinfoga exited with code 1
```

**Comment by KamilLenica** [comment]
In the meantime before official containeer is provided You can clone repo and run build locally using included Dockerfile

**Comment by sundowndev** [comment]
[Docker image](https://hub.docker.com/r/sundowndev/phoneinfoga/tags?page=1&ordering=last_updated) is now available for amd64, arm/v7 & arm64. Could you please try again ? Thanks

**Comment by kllngtme** [comment]
@sundowndev , thankyou. It is loading and working on a raspberry pi 4 now with no issues using stable. One thing I noticed though, trying to search with the webui using the correct E164 numbering doesn't pull up anything and shows "Parameter 'number' must be a valid integer". Using the correct E164 numbering through the CLI IS working without issues though. The example number on the webui used as well as the CLI is 14155552671 as well as +14155552671.

**Comment by KamilLenica** [comment]
@sundowndev  Just verified, Container starts up without issues
WebGUI has problem as described by @kllngtme

**Comment by sundowndev** [comment]
Just tried using the demo and master branch, it works well:

```
$ curl -X GET http://localhost:5000/api/numbers/14155552671/scan/local

{"success":true,"error":"","result":{"rawLocal":"4155552671","local":"(415) 555-2671","E164":"+14155552671","international":"14155552671","countryCode":1,"country":"US","carrier":""}}
```

Could you take a look at the network tab to see what's wrong with the request ?

**Comment by kllngtme** [comment]
@sundowndev not sure what you mean by network tab

**Comment by sundowndev** [comment]
> @sundowndev not sure what you mean by network tab

I mean the network tab of the developer tool of your browser. For example, press F12 if you're using Firefox. Ensure to open it before the scan, then click on the errored HTTP request.

**Comment by kllngtme** [comment]
{success: false, error: "Parameter 'number' must be a valid integer."}
error: "Parameter 'number' must be a valid integer."
success: false

**Comment by KamilLenica** [comment]
@sundowndev i am pretty sure this is problem with frontend. Console commands are working without problem

**Comment by sundowndev** [comment]
> @sundowndev i am pretty sure this is problem with frontend. Console commands are working without problem

The API responds with an error so the issue comes from the web backend.

Could you provide the complete URL of that request ? Also what's the version you're running on?

**Comment by kllngtme** [comment]
http://192.168.1.226:5000/api/numbers/14155552671/scan/local

{success: false, error: "Parameter 'number' must be a valid integer."}
error: "Parameter 'number' must be a valid integer."
success: false

**Comment by sundowndev** [comment]
> http://192.168.1.226:5000/api/numbers/14155552671/scan/local
> 
> {success: false, error: "Parameter 'number' must be a valid integer."}
> error: "Parameter 'number' must be a valid integer."
> success: false

@kllngtme Thanks. What response do you get from http://192.168.1.226:5000/api please ? This is gonna be hard to fix if I cannot reproduce it 😕

**Comment by sundowndev** [comment]
I pushed a quick path on the master branch to help us troubleshoot this. Could you pull Docker image on the [latest tag](https://hub.docker.com/layers/sundowndev/phoneinfoga/latest/images/sha256-896257dfd819fab016d4420f60a909824a219e329720a1cd605d6e56e58527db?context=explore) and try again? The error will still be here but it should be more explicit. Be sure to use linux/amd64 arch to run this image. Thanks!

**Comment by kllngtme** [comment]
> {success: false, error: "Parameter 'number' must be a valid integer."}
> error: "Parameter 'number' must be a valid integer."
> success: false

This is the response:
{success: false, error: "Parameter 'number' must be a valid integer."}
error: "Parameter 'number' must be a valid integer."
success: false

**Comment by sundowndev** [comment]
> > {success: false, error: "Parameter 'number' must be a valid integer."}
> > error: "Parameter 'number' must be a valid integer."
> > success: false
> 
> This is the response:
> {success: false, error: "Parameter 'number' must be a valid integer."}
> error: "Parameter 'number' must be a valid integer."
> success: false

No I meant the response of that particular URL : http://192.168.1.226:5000/api it's supposed to give information about the current Phoneinfoga version.

**Comment by kllngtme** [comment]
Mine isn't showing the version:
The response is {"success":true,"version":"","commit":""}

I'm using stable as well as latest still crashes and comes up with:
phoneinfoga    | standard_init_linux.go:219: exec user process caused: exec format error

**Comment by sundowndev** [comment]
> I'm using stable as well as latest still crashes and comes up with:
> phoneinfoga | standard_init_linux.go:219: exec user process caused: exec format error

Yes, as I said, the latest tag is updated from the master branch and is only compatible with linux/amd64.

> Mine isn't showing the version:
> The response is {"success":true,"version":"","commit":""}

Very strange, I'll to reproduce that

**Comment by root9191** [comment]
How do i use this Image on the Raspi 4? 
I have this architecture: Linux_aarch64
Do i just need to clone the Repo, modify the docker-compose.yml with the "build: ." Parameter and rund docker-compose build?
